-- public.base_sys_conf definition

-- Drop table

-- DROP TABLE public.base_sys_conf;

CREATE TABLE public.base_sys_conf (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	c_key varchar(255) NOT NULL,
	c_value text NOT NULL,
	CONSTRAINT base_sys_conf_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX auto_idx_base_sys_conf_c_key ON public.base_sys_conf USING btree (c_key);


-- public.base_sys_department definition

-- Drop table

-- DROP TABLE public.base_sys_department;

CREATE TABLE public.base_sys_department (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	"name" varchar(255) NOT NULL,
	parent_id int8 NULL,
	order_num int4 DEFAULT 0 NULL,
	CONSTRAINT base_sys_department_pkey PRIMARY KEY (id)
);


-- public.base_sys_log definition

-- Drop table

-- DROP TABLE public.base_sys_log;

CREATE TABLE public.base_sys_log (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	user_id int8 NULL,
	"action" varchar(1000) NULL,
	ip varchar(50) NULL,
	params json NULL,
	CONSTRAINT base_sys_log_pkey PRIMARY KEY (id)
);
CREATE INDEX auto_idx_base_sys_log_user_id ON public.base_sys_log USING btree (user_id);


-- public.base_sys_menu definition

-- Drop table

-- DROP TABLE public.base_sys_menu;

CREATE TABLE public.base_sys_menu (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	parent_id int8 NULL,
	"name" varchar(255) NULL,
	perms text NULL,
	"type" int4 DEFAULT 0 NULL,
	icon varchar(255) NULL,
	order_num int4 DEFAULT 0 NULL,
	router varchar(255) NULL,
	view_path varchar(255) NULL,
	keep_alive bool DEFAULT true NULL,
	is_show bool DEFAULT true NULL,
	CONSTRAINT base_sys_menu_pkey PRIMARY KEY (id)
);
CREATE INDEX auto_idx_base_sys_menu_parent_id ON public.base_sys_menu USING btree (parent_id);


-- public.base_sys_param definition

-- Drop table

-- DROP TABLE public.base_sys_param;

CREATE TABLE public.base_sys_param (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	key_name varchar(255) NOT NULL,
	"name" varchar(255) NULL,
	"data" text NULL,
	data_type int4 DEFAULT 0 NULL,
	remark varchar(255) NULL,
	CONSTRAINT base_sys_param_pkey PRIMARY KEY (id)
);
CREATE INDEX auto_idx_base_sys_param_key_name ON public.base_sys_param USING btree (key_name);


-- public.base_sys_role definition

-- Drop table

-- DROP TABLE public.base_sys_role;

CREATE TABLE public.base_sys_role (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	user_id int8 NOT NULL,
	"name" varchar(255) NOT NULL,
	"label" varchar(255) NOT NULL,
	remark varchar(255) NULL,
	relevance int4 DEFAULT 1 NULL,
	menu_id_list json NULL,
	department_id_list json NULL,
	CONSTRAINT base_sys_role_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX auto_idx_base_sys_role_label ON public.base_sys_role USING btree (label);
CREATE INDEX auto_idx_base_sys_role_user_id ON public.base_sys_role USING btree (user_id);


-- public.base_sys_role_department definition

-- Drop table

-- DROP TABLE public.base_sys_role_department;

CREATE TABLE public.base_sys_role_department (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	role_id int8 NULL,
	department_id int8 NULL,
	CONSTRAINT base_sys_role_department_pkey PRIMARY KEY (id)
);


-- public.base_sys_role_menu definition

-- Drop table

-- DROP TABLE public.base_sys_role_menu;

CREATE TABLE public.base_sys_role_menu (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	menu_id int8 NULL,
	role_id int8 NULL,
	CONSTRAINT base_sys_role_menu_pkey PRIMARY KEY (id)
);


-- public.base_sys_user definition

-- Drop table

-- DROP TABLE public.base_sys_user;

CREATE TABLE public.base_sys_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	tenant_id int8 NULL,
	department_id int8 NULL,
	"name" varchar(255) NULL,
	username varchar(100) NOT NULL,
	"password" varchar(255) NOT NULL,
	password_v int4 DEFAULT 1 NULL,
	nick_name varchar(255) NOT NULL,
	head_img varchar(255) NULL,
	phone varchar(255) NULL,
	email varchar(255) NULL,
	remark varchar(255) NULL,
	status int4 DEFAULT 1 NULL,
	socket_id varchar(255) NULL,
	CONSTRAINT base_sys_user_pkey PRIMARY KEY (id)
);
CREATE INDEX auto_idx_base_sys_user_department_id ON public.base_sys_user USING btree (department_id);
CREATE INDEX auto_idx_base_sys_user_tenant_id ON public.base_sys_user USING btree (tenant_id);
CREATE UNIQUE INDEX auto_idx_base_sys_user_username ON public.base_sys_user USING btree (username);


-- public.base_sys_user_role definition

-- Drop table

-- DROP TABLE public.base_sys_user_role;

CREATE TABLE public.base_sys_user_role (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	user_id int8 NULL,
	role_id int8 NULL,
	CONSTRAINT base_sys_user_role_pkey PRIMARY KEY (id)
);
CREATE INDEX auto_idx_base_sys_user_role_role_id ON public.base_sys_user_role USING btree (role_id);
CREATE INDEX auto_idx_base_sys_user_role_user_id ON public.base_sys_user_role USING btree (user_id);